<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>

        <meta charset="utf-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge">   
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1') ?>
        <?php echo $this->headTitle('Start Site')->setSeparator(' - ')->setAutoEscape(false) ?> 

        <!-- Le styles -->
        <?php
        echo $this->headLink(
                //array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', '
                //   href' => $this->basePath() . '/images/favicon.ico')
                )
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->

<?php
echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->appendFile($this->basePath() . '/js/bootstrap.min.js')
?>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body>

        <?php echo $this->content; ?>

    </body>
    
    <?php
    $analyticsCode = '\'UA-XXXXX-X\'';
    $analyticsConfigFile = dirname(dirname(dirname(dirname(dirname(__DIR__))))) . '/config/autoload/google-analytics.php';
    
    if( file_exists($analyticsConfig) ) {
        $analyticsConfig = include $analyticsConfigFile;
        if (isset($analyticsConfig['analytics_code']) && !empty($analyticsConfig['analytics_code'])) {
            $analyticsCode = '\'' . $analyticsConfig['analytics_code'] . '\'';
        }
    }
    ?>

    <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create',<?php echo $analyticsCode; ?>);ga('send','pageview');
    </script>
    
</html>